# -----------------------------------------------------------------------------
# Ubuntu-based Virtual Networking Image (x64) - SoftEther VPN Server
#
# Features:
#   Parametric Design.
#   Support for Legacy/Traditional Remote administration.
#     Administration & Diagnostic Tools.
#   Configuration Management (confd).
#     Boot-time dependency injection.
#     Network settings reinitialization on reboot.
#   Process Management (supervisor)
#   Cloud-based Monitoring and Application Performance Management (Loggly & NewRelic).
#   Configuration Store & Service Discovery Service (Consul)
#   Secure Virtual Network Client (SoftEther).
#
#   Virtual Networking Serivces (SoftEther VPN Server).
# -----------------------------------------------------------------------------
# https://github.com/cveira/docker-vnet-softether
# -----------------------------------------------------------------------------


FROM ubuntu:14.04
MAINTAINER Carlos Veira Lorenzo "cveira@thinkinbig.org"


# -----------------------------------------------------------------------------
# Docker environment

ENV DEBIAN_FRONTEND noninteractive

ENV SOFTETHER_VERSION {{getv "/meta/softether/version"}}
ENV CONFD_VERSION {{getv "/meta/confd/version"}}
ENV CONSUL_VERSION {{getv "/meta/consul/version"}}


# -----------------------------------------------------------------------------
# Package deployment

RUN mkdir /root/tmp
WORKDIR /root/tmp

RUN \
  export LANGUAGE=en_US.UTF-8 && \
  export LANG=en_US.UTF-8 && \
  export LC_ALL=en_US.UTF-8 && \
  locale-gen en_US.UTF-8 && \
  dpkg-reconfigure locales

RUN \
  apt-get update && \
  apt-get install -y bash curl lftp wget git htop mc man zip unzip vim nano ltrace strace multitail openssh-server supervisor monit nmap socat dnsutils traceroute gnupg

RUN \
  apt-get update && \
  apt-get install -y build-essential && \
  apt-get install -y python

RUN \
  echo "deb http://apt.newrelic.com/debian/ newrelic non-free" >> /etc/apt/sources.list.d/newrelic.list && \
  wget -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
  apt-get update && \
  apt-get install -y newrelic-sysmond newrelic-daemon

RUN \
  wget -O - https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python && \
  pip install newrelic-plugin-agent && \
  cp /opt/newrelic-plugin-agent/newrelic-plugin-agent.cfg /etc/newrelic/ && \
  cp /opt/newrelic-plugin-agent/newrelic-plugin-agent.deb /etc/init.d/newrelic-plugin-agent && \
  chmod 755 /etc/init.d/newrelic-plugin-agent && \
  mkdir -p /var/run/newrelic

RUN \
  wget -O /root/tmp/softether-vpnclient-linux-x86-64bit.tar.gz http://www.softether-download.com/files/softether/${SOFTETHER_VERSION}-tree/Linux/SoftEther%20VPN%20Client/64bit%20-%20Intel%20x64%20or%20AMD64/softether-vpnclient-${SOFTETHER_VERSION}-linux-x64-64bit.tar.gz && \
  tar -xzvf softether-vpnclient-linux-x86-64bit.tar.gz && \
  cd vpnclient && \
  make i_read_and_agree_the_license_agreement && \
  cd .. && \
  mv vpnclient /usr/local && \
  cd /usr/local/vpnclient/ && \
  chmod 600 * && \
  chmod 700 vpnclient && \
  chmod 700 vpncmd && \
  rm -f /root/tmp/softether-vpnclient-linux-x86-64bit.tar.gz

RUN \
  wget -O /root/tmp/confd https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64 && \
  mv /root/tmp/confd /usr/local/bin/confd && \
  chmod +x /usr/local/bin/confd && \
  mkdir -p /etc/confd/conf.d && \
  mkdir -p /etc/confd/templates
COPY settings/confd/ /etc/confd/

ADD https://dl.bintray.com/mitchellh/consul/${CONSUL_VERSION}_linux_amd64.zip /tmp/consul.zip
RUN \
  cd /bin && \
  unzip /tmp/consul.zip && \
  chmod +x /bin/consul && \
  rm -f /tmp/consul.zip

COPY settings/init-vpnserver.sh /etc/init.d/vpnserver
RUN \
  wget -O /root/tmp/softether-vpnserver-linux-x86-64bit.tar.gz http://www.softether-download.com/files/softether/${SOFTETHER_VERSION}-tree/Linux/SoftEther%20VPN%20Server/64bit%20-%20Intel%20x64%20or%20AMD64/softether-vpnserver-${SOFTETHER_VERSION}-linux-x64-64bit.tar.gz && \
  tar -xzvf softether-vpnserver-linux-x86-64bit.tar.gz && \
  cd vpnserver && \
  make i_read_and_agree_the_license_agreement && \
  cd .. && \
  mv vpnserver /usr/local && \
  cd /usr/local/vpnserver/ && \
  chmod 600 * && \
  chmod 700 vpnserver && \
  chmod 700 vpncmd && \
  mkdir -p mkdir /var/lock/subsys && \
  chmod 755 /etc/init.d/vpnserver && \
  update-rc.d vpnserver defaults && \
  rm -f /root/tmp/softether-vpnserver-linux-x86-64bit.tar.gz

RUN apt-get clean -qq


# -----------------------------------------------------------------------------
# System configuration

RUN echo 'root:{{getv "/meta/node/admin/defaultpasswd"}}' | chpasswd

RUN \
  echo "Europe/Amsterdam" > /etc/timezone && \
  dpkg-reconfigure -f noninteractive tzdata

RUN \
  nrsysmond-config --set license_key={{getv "/meta/cloud/newrelic/licensekey"}} && \
  cp /etc/newrelic/newrelic.cfg.template /etc/newrelic/newrelic.cfg && \
  sed -i -e 's/REPLACE_WITH_REAL_KEY/{{getv "/meta/cloud/newrelic/licensekey"}}/g' /etc/newrelic/newrelic-plugin-agent.cfg

RUN \
  mkdir /var/run/sshd && \
  sed -i "s/UsePAM.*/UsePAM yes/g"                   /etc/ssh/sshd_config && \
  sed -i "s/PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config

RUN \
  touch /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  chown syslog:adm /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  chmod 640 /var/log/syslog /var/log/kern.log /var/log/debug /var/log/mail.log /var/log/mail.err && \
  sed -i 's/^[#\t\s]*\(\*\.=notice;\*\.=warn\).*xconsole$/\t\1\t\-\/var\/log\/syslog/' /etc/rsyslog.d/50-default.conf

COPY settings/rsyslog-modload.conf           /etc/rsyslog.d/0-rsyslog-modload.conf
COPY settings/loggly-sysauth.conf            /etc/rsyslog.d/5-loggly-sysauth.conf
COPY settings/loggly-monit.conf              /etc/rsyslog.d/8-loggly-monit.conf
COPY settings/loggly-supervisord.conf        /etc/rsyslog.d/9-loggly-supervisord.conf
COPY settings/loggly-newrelic-sysmond.conf   /etc/rsyslog.d/10-loggly-newrelic-sysmond.conf
COPY settings/loggly-newrelic-daemon.conf    /etc/rsyslog.d/11-loggly-newrelic-daemon.conf
COPY settings/loggly-newrelic-pa.conf        /etc/rsyslog.d/12-loggly-newrelic-pa.conf
COPY settings/loggly.conf                    /etc/rsyslog.d/22-loggly.conf

RUN mkdir -p /var/log/supervisor
COPY settings/monit-system.conf   /etc/monit/conf.d/
COPY settings/monit-services.conf /etc/monit/conf.d/

RUN mkdir -p /etc/consul/
COPY         ./settings/consul/ /etc/consul/
ONBUILD COPY ./settings/consul/ /etc/consul/


# -----------------------------------------------------------------------------
# Shell environment configuration

COPY settings/.profile             /root/
COPY settings/.profile_preferences /root/
COPY settings/ssh/                 /root/.ssh/
COPY settings/scripts/             /root/scripts/

RUN chmod u+x /root/scripts/*.sh


# -----------------------------------------------------------------------------
# Container execution

WORKDIR /root
EXPOSE 22 2812 9001 443 992 1194 5555 8300 8301 8301/udp 8302 8302/udp 8400 8500

CMD ["/root/scripts/init.sh"]